---
driver:
  ## vagrant
  #  name: vagrant
  ## docker
  # from http://www.tddfellow.com/blog/2015/08/05/running-kitchen-docker-tests-with-upstart/
  name: docker
  use_sudo: false
  disable_upstart: false
  image: ubuntu-upstart:14.04
  run_command: /sbin/init

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_version: latest
  ansible_verbosity: 2
  ansible_verbose: true
  extra_vars:
    env: "corp"

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    provisioner:
      require_ansible_repo: false
      require_ansible_source: true
      # ansible_source_url: 'git://github.com/aerickson/ansible.git'
      # playbook: test/integration/default/default.yml
