---
driver:
  ## vagrant
  name: vagrant
  ## docker
  # from http://www.tddfellow.com/blog/2015/08/05/running-kitchen-docker-tests-with-upstart/
  # name: docker
  # use_sudo: false
  # disable_upstart: false
  # image: ubuntu-upstart:14.04
  # run_command: /sbin/init

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_version: latest
  # https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md
  # 2 is warn, 3 is debug
  ansible_verbosity: 3
  ansible_verbose: true
  extra_vars:
    env: "corp"

platforms:
  - name: ubuntu-14.04

suites:
  - name: file_example
    provisioner:
      require_ansible_repo: false
      require_ansible_source: true
      #ansible_source_url: 'git://github.com/aerickson/ansible.git'
      #ansible_source_rev: hlajf_v2
  # - name: template_example
  #   provisioner:
  #     require_ansible_repo: false
  #     require_ansible_source: true
  #     #ansible_source_url: 'git://github.com/aerickson/ansible.git'
  #     #ansible_source_rev: hlajf_v2
