---

# always works as it's never hard linked
- name: copy file
  copy: src="test_file" dest=/etc/test_file_noprob owner=root group=root mode=644

- name: copy file
  copy: src=test_file dest=/etc/test_file owner=root group=root mode=644

# simulates an app creating a chroot via hard linking
# - in my env, nomad starting an app with the isolated exec driver and hardlinking /etc files
- name: make hard link
  file:
    src: /etc/test_file
    dest: /etc/test_file_hardlink
    state: hard

- name: demonstrate file/copy bug
  copy: src=test_file dest=/etc/test_file owner=root group=root mode=644
